name: TodoApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: ja
  xcodeVersion: "15.0"

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.6.0

settings:
  SWIFT_VERSION: "5.9"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  SWIFT_OPTIMIZATION_LEVEL: "-Onone"
  GCC_OPTIMIZATION_LEVEL: "0"

targets:
  TodoApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
      - path: AppDelegate.swift
      - path: SceneDelegate.swift
    dependencies:
      - package: SnapKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.todoapp
      INFOPLIST_FILE: Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      SWIFT_EMIT_LOC_STRINGS: "YES"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: TodoApp
        CFBundleIdentifier: com.example.todoapp
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false

schemes:
  TodoApp:
    build:
      targets:
        TodoApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 